---
- name: Install Jinja2
  pip:
    name: jinja2

- name: Install Bind 9
  apt: 
    name: bind9

- name: Stop the Bind 9 service to run with supervisor
  systemd:
    name: bind9
    state: stopped
    enabled: no

- name: Bind9 Config generator
  copy:
    src: setup_dns_zone
    dest: /usr/local/bin/setup_dns_zone
    mode: "0755"

- name: Setup bind9 supervisor config
  copy:
    src: supervisord_bind
    dest: /etc/supervisor/conf.d/bind.conf
    owner: root
    group: root
    mode: "0755"
