---

- name: Install the Consul Cloud Configure Script
  copy:
    src: consul_cloud_setup
    dest: /usr/local/bin/consul_cloud_setup
    owner: root
    group: root
    mode: "0755"

- name: Setup supervisor config
  copy:
    src: supervisord_consul
    dest: /etc/supervisor/conf.d/consul.conf
    owner: root
    group: root
    mode: "0755"
