---

- name: force bootstrap load
  command: /etc/init.d/ec2_bootstrap 

- name: force reload of supervisor
  command: /usr/local/bin/supervisorctl update

- name: force service starts
  command: /usr/local/bin/supervisorctl start all
