---
# tasks file for shokunin.ansible-cloud-consul
- include: binary_install.yml
- include: template_install.yml
- include: cloud_configure.yml
- { include: bind_setup.yml, when: consul_server_bind }
- { include: force_start.yml, when: consul_force_start }
