# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#
@ansible_home = "/home/vagrant/.ansible"


Vagrant.configure("2") do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.vm.box_url = 'https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64-vagrant.box'
  config.vm.hostname    = "ansible-test"
  config.vm.provision "shell" do |s|
    s.inline = 'if [ ! -f /tmp/initial_config ] ; then  sudo service ssh restart && sudo apt update && sudo apt -y install python python-dev python-pip python-jinja2 python-markupsafe git && sudo pip install --upgrade pip && sudo pip install ansible > /dev/null 2>&1 && touch /tmp/initial_config ; fi '
  end

  config.vm.provision "shell", inline: "chown vagrant:vagrant #{@ansible_home}"

  config.vm.synced_folder "../", "#{@ansible_home}/roles/shokunin.ansible-cloud-consul", type: 'rsync'
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "test.yml"
  end
end

